//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ntp_projekt.soap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/", ConfigurationName="soap.TextCasingSoapType")]
    public interface TextCasingSoapType {
        
        // CODEGEN: Generating message contract since element name sText from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ntp_projekt.soap.TitleCaseWordsWithTokenResponse TitleCaseWordsWithToken(ntp_projekt.soap.TitleCaseWordsWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ntp_projekt.soap.TitleCaseWordsWithTokenResponse> TitleCaseWordsWithTokenAsync(ntp_projekt.soap.TitleCaseWordsWithTokenRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ntp_projekt.soap.InvertStringCaseResponse InvertStringCase(ntp_projekt.soap.InvertStringCaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ntp_projekt.soap.InvertStringCaseResponse> InvertStringCaseAsync(ntp_projekt.soap.InvertStringCaseRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousResponse InvertCaseFirstAdjustStringToPrevious(ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousResponse> InvertCaseFirstAdjustStringToPreviousAsync(ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentResponse InvertCaseFirstAdjustStringToCurrent(ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentResponse> InvertCaseFirstAdjustStringToCurrentAsync(ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ntp_projekt.soap.AllUppercaseWithTokenResponse AllUppercaseWithToken(ntp_projekt.soap.AllUppercaseWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ntp_projekt.soap.AllUppercaseWithTokenResponse> AllUppercaseWithTokenAsync(ntp_projekt.soap.AllUppercaseWithTokenRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ntp_projekt.soap.AllLowercaseWithTokenResponse AllLowercaseWithToken(ntp_projekt.soap.AllLowercaseWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ntp_projekt.soap.AllLowercaseWithTokenResponse> AllLowercaseWithTokenAsync(ntp_projekt.soap.AllLowercaseWithTokenRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ntp_projekt.soap.UppercaseWordsWithTokenResponse UppercaseWordsWithToken(ntp_projekt.soap.UppercaseWordsWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ntp_projekt.soap.UppercaseWordsWithTokenResponse> UppercaseWordsWithTokenAsync(ntp_projekt.soap.UppercaseWordsWithTokenRequest request);
        
        // CODEGEN: Generating message contract since element name sAString from namespace http://www.dataaccess.com/webservicesserver/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ntp_projekt.soap.LowercaseWordsWithTokenResponse LowercaseWordsWithToken(ntp_projekt.soap.LowercaseWordsWithTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ntp_projekt.soap.LowercaseWordsWithTokenResponse> LowercaseWordsWithTokenAsync(ntp_projekt.soap.LowercaseWordsWithTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TitleCaseWordsWithTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TitleCaseWordsWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.TitleCaseWordsWithTokenRequestBody Body;
        
        public TitleCaseWordsWithTokenRequest() {
        }
        
        public TitleCaseWordsWithTokenRequest(ntp_projekt.soap.TitleCaseWordsWithTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class TitleCaseWordsWithTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public TitleCaseWordsWithTokenRequestBody() {
        }
        
        public TitleCaseWordsWithTokenRequestBody(string sText, string sToken) {
            this.sText = sText;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TitleCaseWordsWithTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TitleCaseWordsWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.TitleCaseWordsWithTokenResponseBody Body;
        
        public TitleCaseWordsWithTokenResponse() {
        }
        
        public TitleCaseWordsWithTokenResponse(ntp_projekt.soap.TitleCaseWordsWithTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class TitleCaseWordsWithTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TitleCaseWordsWithTokenResult;
        
        public TitleCaseWordsWithTokenResponseBody() {
        }
        
        public TitleCaseWordsWithTokenResponseBody(string TitleCaseWordsWithTokenResult) {
            this.TitleCaseWordsWithTokenResult = TitleCaseWordsWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertStringCaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertStringCase", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.InvertStringCaseRequestBody Body;
        
        public InvertStringCaseRequest() {
        }
        
        public InvertStringCaseRequest(ntp_projekt.soap.InvertStringCaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertStringCaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        public InvertStringCaseRequestBody() {
        }
        
        public InvertStringCaseRequestBody(string sAString) {
            this.sAString = sAString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertStringCaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertStringCaseResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.InvertStringCaseResponseBody Body;
        
        public InvertStringCaseResponse() {
        }
        
        public InvertStringCaseResponse(ntp_projekt.soap.InvertStringCaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertStringCaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertStringCaseResult;
        
        public InvertStringCaseResponseBody() {
        }
        
        public InvertStringCaseResponseBody(string InvertStringCaseResult) {
            this.InvertStringCaseResult = InvertStringCaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToPreviousRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToPrevious", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousRequestBody Body;
        
        public InvertCaseFirstAdjustStringToPreviousRequest() {
        }
        
        public InvertCaseFirstAdjustStringToPreviousRequest(ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToPreviousRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        public InvertCaseFirstAdjustStringToPreviousRequestBody() {
        }
        
        public InvertCaseFirstAdjustStringToPreviousRequestBody(string sAString) {
            this.sAString = sAString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToPreviousResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToPreviousResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousResponseBody Body;
        
        public InvertCaseFirstAdjustStringToPreviousResponse() {
        }
        
        public InvertCaseFirstAdjustStringToPreviousResponse(ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToPreviousResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertCaseFirstAdjustStringToPreviousResult;
        
        public InvertCaseFirstAdjustStringToPreviousResponseBody() {
        }
        
        public InvertCaseFirstAdjustStringToPreviousResponseBody(string InvertCaseFirstAdjustStringToPreviousResult) {
            this.InvertCaseFirstAdjustStringToPreviousResult = InvertCaseFirstAdjustStringToPreviousResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToCurrentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToCurrent", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentRequestBody Body;
        
        public InvertCaseFirstAdjustStringToCurrentRequest() {
        }
        
        public InvertCaseFirstAdjustStringToCurrentRequest(ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToCurrentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        public InvertCaseFirstAdjustStringToCurrentRequestBody() {
        }
        
        public InvertCaseFirstAdjustStringToCurrentRequestBody(string sAString) {
            this.sAString = sAString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvertCaseFirstAdjustStringToCurrentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvertCaseFirstAdjustStringToCurrentResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentResponseBody Body;
        
        public InvertCaseFirstAdjustStringToCurrentResponse() {
        }
        
        public InvertCaseFirstAdjustStringToCurrentResponse(ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class InvertCaseFirstAdjustStringToCurrentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvertCaseFirstAdjustStringToCurrentResult;
        
        public InvertCaseFirstAdjustStringToCurrentResponseBody() {
        }
        
        public InvertCaseFirstAdjustStringToCurrentResponseBody(string InvertCaseFirstAdjustStringToCurrentResult) {
            this.InvertCaseFirstAdjustStringToCurrentResult = InvertCaseFirstAdjustStringToCurrentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllUppercaseWithTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllUppercaseWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.AllUppercaseWithTokenRequestBody Body;
        
        public AllUppercaseWithTokenRequest() {
        }
        
        public AllUppercaseWithTokenRequest(ntp_projekt.soap.AllUppercaseWithTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllUppercaseWithTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public AllUppercaseWithTokenRequestBody() {
        }
        
        public AllUppercaseWithTokenRequestBody(string sAString, string sToken) {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllUppercaseWithTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllUppercaseWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.AllUppercaseWithTokenResponseBody Body;
        
        public AllUppercaseWithTokenResponse() {
        }
        
        public AllUppercaseWithTokenResponse(ntp_projekt.soap.AllUppercaseWithTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllUppercaseWithTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AllUppercaseWithTokenResult;
        
        public AllUppercaseWithTokenResponseBody() {
        }
        
        public AllUppercaseWithTokenResponseBody(string AllUppercaseWithTokenResult) {
            this.AllUppercaseWithTokenResult = AllUppercaseWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllLowercaseWithTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllLowercaseWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.AllLowercaseWithTokenRequestBody Body;
        
        public AllLowercaseWithTokenRequest() {
        }
        
        public AllLowercaseWithTokenRequest(ntp_projekt.soap.AllLowercaseWithTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllLowercaseWithTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public AllLowercaseWithTokenRequestBody() {
        }
        
        public AllLowercaseWithTokenRequestBody(string sAString, string sToken) {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllLowercaseWithTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllLowercaseWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.AllLowercaseWithTokenResponseBody Body;
        
        public AllLowercaseWithTokenResponse() {
        }
        
        public AllLowercaseWithTokenResponse(ntp_projekt.soap.AllLowercaseWithTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class AllLowercaseWithTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AllLowercaseWithTokenResult;
        
        public AllLowercaseWithTokenResponseBody() {
        }
        
        public AllLowercaseWithTokenResponseBody(string AllLowercaseWithTokenResult) {
            this.AllLowercaseWithTokenResult = AllLowercaseWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UppercaseWordsWithTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UppercaseWordsWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.UppercaseWordsWithTokenRequestBody Body;
        
        public UppercaseWordsWithTokenRequest() {
        }
        
        public UppercaseWordsWithTokenRequest(ntp_projekt.soap.UppercaseWordsWithTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class UppercaseWordsWithTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public UppercaseWordsWithTokenRequestBody() {
        }
        
        public UppercaseWordsWithTokenRequestBody(string sAString, string sToken) {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UppercaseWordsWithTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UppercaseWordsWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.UppercaseWordsWithTokenResponseBody Body;
        
        public UppercaseWordsWithTokenResponse() {
        }
        
        public UppercaseWordsWithTokenResponse(ntp_projekt.soap.UppercaseWordsWithTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class UppercaseWordsWithTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UppercaseWordsWithTokenResult;
        
        public UppercaseWordsWithTokenResponseBody() {
        }
        
        public UppercaseWordsWithTokenResponseBody(string UppercaseWordsWithTokenResult) {
            this.UppercaseWordsWithTokenResult = UppercaseWordsWithTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LowercaseWordsWithTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LowercaseWordsWithToken", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.LowercaseWordsWithTokenRequestBody Body;
        
        public LowercaseWordsWithTokenRequest() {
        }
        
        public LowercaseWordsWithTokenRequest(ntp_projekt.soap.LowercaseWordsWithTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class LowercaseWordsWithTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sAString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sToken;
        
        public LowercaseWordsWithTokenRequestBody() {
        }
        
        public LowercaseWordsWithTokenRequestBody(string sAString, string sToken) {
            this.sAString = sAString;
            this.sToken = sToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LowercaseWordsWithTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LowercaseWordsWithTokenResponse", Namespace="http://www.dataaccess.com/webservicesserver/", Order=0)]
        public ntp_projekt.soap.LowercaseWordsWithTokenResponseBody Body;
        
        public LowercaseWordsWithTokenResponse() {
        }
        
        public LowercaseWordsWithTokenResponse(ntp_projekt.soap.LowercaseWordsWithTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class LowercaseWordsWithTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LowercaseWordsWithTokenResult;
        
        public LowercaseWordsWithTokenResponseBody() {
        }
        
        public LowercaseWordsWithTokenResponseBody(string LowercaseWordsWithTokenResult) {
            this.LowercaseWordsWithTokenResult = LowercaseWordsWithTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TextCasingSoapTypeChannel : ntp_projekt.soap.TextCasingSoapType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextCasingSoapTypeClient : System.ServiceModel.ClientBase<ntp_projekt.soap.TextCasingSoapType>, ntp_projekt.soap.TextCasingSoapType {
        
        public TextCasingSoapTypeClient() {
        }
        
        public TextCasingSoapTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextCasingSoapTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextCasingSoapTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextCasingSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntp_projekt.soap.TitleCaseWordsWithTokenResponse ntp_projekt.soap.TextCasingSoapType.TitleCaseWordsWithToken(ntp_projekt.soap.TitleCaseWordsWithTokenRequest request) {
            return base.Channel.TitleCaseWordsWithToken(request);
        }
        
        public string TitleCaseWordsWithToken(string sText, string sToken) {
            ntp_projekt.soap.TitleCaseWordsWithTokenRequest inValue = new ntp_projekt.soap.TitleCaseWordsWithTokenRequest();
            inValue.Body = new ntp_projekt.soap.TitleCaseWordsWithTokenRequestBody();
            inValue.Body.sText = sText;
            inValue.Body.sToken = sToken;
            ntp_projekt.soap.TitleCaseWordsWithTokenResponse retVal = ((ntp_projekt.soap.TextCasingSoapType)(this)).TitleCaseWordsWithToken(inValue);
            return retVal.Body.TitleCaseWordsWithTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntp_projekt.soap.TitleCaseWordsWithTokenResponse> ntp_projekt.soap.TextCasingSoapType.TitleCaseWordsWithTokenAsync(ntp_projekt.soap.TitleCaseWordsWithTokenRequest request) {
            return base.Channel.TitleCaseWordsWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntp_projekt.soap.TitleCaseWordsWithTokenResponse> TitleCaseWordsWithTokenAsync(string sText, string sToken) {
            ntp_projekt.soap.TitleCaseWordsWithTokenRequest inValue = new ntp_projekt.soap.TitleCaseWordsWithTokenRequest();
            inValue.Body = new ntp_projekt.soap.TitleCaseWordsWithTokenRequestBody();
            inValue.Body.sText = sText;
            inValue.Body.sToken = sToken;
            return ((ntp_projekt.soap.TextCasingSoapType)(this)).TitleCaseWordsWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntp_projekt.soap.InvertStringCaseResponse ntp_projekt.soap.TextCasingSoapType.InvertStringCase(ntp_projekt.soap.InvertStringCaseRequest request) {
            return base.Channel.InvertStringCase(request);
        }
        
        public string InvertStringCase(string sAString) {
            ntp_projekt.soap.InvertStringCaseRequest inValue = new ntp_projekt.soap.InvertStringCaseRequest();
            inValue.Body = new ntp_projekt.soap.InvertStringCaseRequestBody();
            inValue.Body.sAString = sAString;
            ntp_projekt.soap.InvertStringCaseResponse retVal = ((ntp_projekt.soap.TextCasingSoapType)(this)).InvertStringCase(inValue);
            return retVal.Body.InvertStringCaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntp_projekt.soap.InvertStringCaseResponse> ntp_projekt.soap.TextCasingSoapType.InvertStringCaseAsync(ntp_projekt.soap.InvertStringCaseRequest request) {
            return base.Channel.InvertStringCaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntp_projekt.soap.InvertStringCaseResponse> InvertStringCaseAsync(string sAString) {
            ntp_projekt.soap.InvertStringCaseRequest inValue = new ntp_projekt.soap.InvertStringCaseRequest();
            inValue.Body = new ntp_projekt.soap.InvertStringCaseRequestBody();
            inValue.Body.sAString = sAString;
            return ((ntp_projekt.soap.TextCasingSoapType)(this)).InvertStringCaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousResponse ntp_projekt.soap.TextCasingSoapType.InvertCaseFirstAdjustStringToPrevious(ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousRequest request) {
            return base.Channel.InvertCaseFirstAdjustStringToPrevious(request);
        }
        
        public string InvertCaseFirstAdjustStringToPrevious(string sAString) {
            ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousRequest inValue = new ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousRequest();
            inValue.Body = new ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousRequestBody();
            inValue.Body.sAString = sAString;
            ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousResponse retVal = ((ntp_projekt.soap.TextCasingSoapType)(this)).InvertCaseFirstAdjustStringToPrevious(inValue);
            return retVal.Body.InvertCaseFirstAdjustStringToPreviousResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousResponse> ntp_projekt.soap.TextCasingSoapType.InvertCaseFirstAdjustStringToPreviousAsync(ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousRequest request) {
            return base.Channel.InvertCaseFirstAdjustStringToPreviousAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousResponse> InvertCaseFirstAdjustStringToPreviousAsync(string sAString) {
            ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousRequest inValue = new ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousRequest();
            inValue.Body = new ntp_projekt.soap.InvertCaseFirstAdjustStringToPreviousRequestBody();
            inValue.Body.sAString = sAString;
            return ((ntp_projekt.soap.TextCasingSoapType)(this)).InvertCaseFirstAdjustStringToPreviousAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentResponse ntp_projekt.soap.TextCasingSoapType.InvertCaseFirstAdjustStringToCurrent(ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentRequest request) {
            return base.Channel.InvertCaseFirstAdjustStringToCurrent(request);
        }
        
        public string InvertCaseFirstAdjustStringToCurrent(string sAString) {
            ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentRequest inValue = new ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentRequest();
            inValue.Body = new ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentRequestBody();
            inValue.Body.sAString = sAString;
            ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentResponse retVal = ((ntp_projekt.soap.TextCasingSoapType)(this)).InvertCaseFirstAdjustStringToCurrent(inValue);
            return retVal.Body.InvertCaseFirstAdjustStringToCurrentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentResponse> ntp_projekt.soap.TextCasingSoapType.InvertCaseFirstAdjustStringToCurrentAsync(ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentRequest request) {
            return base.Channel.InvertCaseFirstAdjustStringToCurrentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentResponse> InvertCaseFirstAdjustStringToCurrentAsync(string sAString) {
            ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentRequest inValue = new ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentRequest();
            inValue.Body = new ntp_projekt.soap.InvertCaseFirstAdjustStringToCurrentRequestBody();
            inValue.Body.sAString = sAString;
            return ((ntp_projekt.soap.TextCasingSoapType)(this)).InvertCaseFirstAdjustStringToCurrentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntp_projekt.soap.AllUppercaseWithTokenResponse ntp_projekt.soap.TextCasingSoapType.AllUppercaseWithToken(ntp_projekt.soap.AllUppercaseWithTokenRequest request) {
            return base.Channel.AllUppercaseWithToken(request);
        }
        
        public string AllUppercaseWithToken(string sAString, string sToken) {
            ntp_projekt.soap.AllUppercaseWithTokenRequest inValue = new ntp_projekt.soap.AllUppercaseWithTokenRequest();
            inValue.Body = new ntp_projekt.soap.AllUppercaseWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            ntp_projekt.soap.AllUppercaseWithTokenResponse retVal = ((ntp_projekt.soap.TextCasingSoapType)(this)).AllUppercaseWithToken(inValue);
            return retVal.Body.AllUppercaseWithTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntp_projekt.soap.AllUppercaseWithTokenResponse> ntp_projekt.soap.TextCasingSoapType.AllUppercaseWithTokenAsync(ntp_projekt.soap.AllUppercaseWithTokenRequest request) {
            return base.Channel.AllUppercaseWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntp_projekt.soap.AllUppercaseWithTokenResponse> AllUppercaseWithTokenAsync(string sAString, string sToken) {
            ntp_projekt.soap.AllUppercaseWithTokenRequest inValue = new ntp_projekt.soap.AllUppercaseWithTokenRequest();
            inValue.Body = new ntp_projekt.soap.AllUppercaseWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ntp_projekt.soap.TextCasingSoapType)(this)).AllUppercaseWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntp_projekt.soap.AllLowercaseWithTokenResponse ntp_projekt.soap.TextCasingSoapType.AllLowercaseWithToken(ntp_projekt.soap.AllLowercaseWithTokenRequest request) {
            return base.Channel.AllLowercaseWithToken(request);
        }
        
        public string AllLowercaseWithToken(string sAString, string sToken) {
            ntp_projekt.soap.AllLowercaseWithTokenRequest inValue = new ntp_projekt.soap.AllLowercaseWithTokenRequest();
            inValue.Body = new ntp_projekt.soap.AllLowercaseWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            ntp_projekt.soap.AllLowercaseWithTokenResponse retVal = ((ntp_projekt.soap.TextCasingSoapType)(this)).AllLowercaseWithToken(inValue);
            return retVal.Body.AllLowercaseWithTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntp_projekt.soap.AllLowercaseWithTokenResponse> ntp_projekt.soap.TextCasingSoapType.AllLowercaseWithTokenAsync(ntp_projekt.soap.AllLowercaseWithTokenRequest request) {
            return base.Channel.AllLowercaseWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntp_projekt.soap.AllLowercaseWithTokenResponse> AllLowercaseWithTokenAsync(string sAString, string sToken) {
            ntp_projekt.soap.AllLowercaseWithTokenRequest inValue = new ntp_projekt.soap.AllLowercaseWithTokenRequest();
            inValue.Body = new ntp_projekt.soap.AllLowercaseWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ntp_projekt.soap.TextCasingSoapType)(this)).AllLowercaseWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntp_projekt.soap.UppercaseWordsWithTokenResponse ntp_projekt.soap.TextCasingSoapType.UppercaseWordsWithToken(ntp_projekt.soap.UppercaseWordsWithTokenRequest request) {
            return base.Channel.UppercaseWordsWithToken(request);
        }
        
        public string UppercaseWordsWithToken(string sAString, string sToken) {
            ntp_projekt.soap.UppercaseWordsWithTokenRequest inValue = new ntp_projekt.soap.UppercaseWordsWithTokenRequest();
            inValue.Body = new ntp_projekt.soap.UppercaseWordsWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            ntp_projekt.soap.UppercaseWordsWithTokenResponse retVal = ((ntp_projekt.soap.TextCasingSoapType)(this)).UppercaseWordsWithToken(inValue);
            return retVal.Body.UppercaseWordsWithTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntp_projekt.soap.UppercaseWordsWithTokenResponse> ntp_projekt.soap.TextCasingSoapType.UppercaseWordsWithTokenAsync(ntp_projekt.soap.UppercaseWordsWithTokenRequest request) {
            return base.Channel.UppercaseWordsWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntp_projekt.soap.UppercaseWordsWithTokenResponse> UppercaseWordsWithTokenAsync(string sAString, string sToken) {
            ntp_projekt.soap.UppercaseWordsWithTokenRequest inValue = new ntp_projekt.soap.UppercaseWordsWithTokenRequest();
            inValue.Body = new ntp_projekt.soap.UppercaseWordsWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ntp_projekt.soap.TextCasingSoapType)(this)).UppercaseWordsWithTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ntp_projekt.soap.LowercaseWordsWithTokenResponse ntp_projekt.soap.TextCasingSoapType.LowercaseWordsWithToken(ntp_projekt.soap.LowercaseWordsWithTokenRequest request) {
            return base.Channel.LowercaseWordsWithToken(request);
        }
        
        public string LowercaseWordsWithToken(string sAString, string sToken) {
            ntp_projekt.soap.LowercaseWordsWithTokenRequest inValue = new ntp_projekt.soap.LowercaseWordsWithTokenRequest();
            inValue.Body = new ntp_projekt.soap.LowercaseWordsWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            ntp_projekt.soap.LowercaseWordsWithTokenResponse retVal = ((ntp_projekt.soap.TextCasingSoapType)(this)).LowercaseWordsWithToken(inValue);
            return retVal.Body.LowercaseWordsWithTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ntp_projekt.soap.LowercaseWordsWithTokenResponse> ntp_projekt.soap.TextCasingSoapType.LowercaseWordsWithTokenAsync(ntp_projekt.soap.LowercaseWordsWithTokenRequest request) {
            return base.Channel.LowercaseWordsWithTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ntp_projekt.soap.LowercaseWordsWithTokenResponse> LowercaseWordsWithTokenAsync(string sAString, string sToken) {
            ntp_projekt.soap.LowercaseWordsWithTokenRequest inValue = new ntp_projekt.soap.LowercaseWordsWithTokenRequest();
            inValue.Body = new ntp_projekt.soap.LowercaseWordsWithTokenRequestBody();
            inValue.Body.sAString = sAString;
            inValue.Body.sToken = sToken;
            return ((ntp_projekt.soap.TextCasingSoapType)(this)).LowercaseWordsWithTokenAsync(inValue);
        }
    }
}
